version: 0.0.1.{build}

clone_folder: C:\GOPATH\src\github.com\osteele\gojekyll

environment:
  GOPATH: C:\GOPATH

init:
  - set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env

install:
  - go get -t ./...
  - pip install Pygments

build_script:
  - go test ./...

platform: x64
