version: 0.0.1.{build}

clone_folder: C:\GOPATH\src\github.com\osteele\gojekyll

environment:
  GOPATH: C:\GOPATH

cache:
  - C:\mingw64 -> appveyor.yml

init:
  - set PATH=C:\mingw64\bin;C:\go\bin;%GOPATH%;%PATH%
  - go version
  - go env
  - set CC=gcc
  - set CXX=g++

install:
  - ps: |
      # Install MinGW.
      $url = "https://bintray.com/artifact/download/drewwells/generic/x86_64-5.1.0-release-win32-seh-rt_v4-rev0.7z"
      $strFileName="C:\mingw64\bin\mingw32-make.exe"
      If (Test-Path $strFileName){
        Write-Host "Using cached mingw64"
      }Else{
        Write-Host "Fetching mingw64"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile ming32-64.7z
        &7z x -oC:\ ming32-64.7z > $null
      }
  - go get -t ./...
  - pip install Pygments

build_script:
  - go test ./...

platform: x64
