build:
  main: main.go
  binary: gojekyll
  ldflags: -s -w -X gojekyll.cmd.Version={{.Version}} -X gojekyll.cmd.BuildDate={{.Date}}
  goos:
    - linux
  goarch:
    - amd64
    - 386
archive:
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: macOS
    linux: Linux
release:
  draft: true
